language: node_js
node_js:
  - '10.16.0'
os:
  - linux
  - osx
before_install:
  - node -v
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install yarn --ignore-dependencies; fi
  - yarn --verison
  - cd app
  - yarn global add node-gyp
  - prefix=`npm prefix -g`
  - globalnodegyp=$prefix"/node_modules/node-gyp/bin/node-gyp.js"
  - npm config set node_gyp $globalnodegyp
  - node-gyp install --target=4.2.2 --dist-url=https://atom.io/download/electron
install:
  - yarn
script:
  - yarn run pack:x64
branches:
  only:
  - master
