language: node_js
node_js:
  - '10.13.0'
os:
  - linux
  - osx
before_install:
  - node -v
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install yarn --without-node; fi
  - yarn --verison
  - cd app
  - yarn global add node-gyp
  - node-gyp install --target=4.0.1 --dist-url=https://atom.io/download/electron
install:
  - yarn
script:
  - yarn run pkg64
branches:
  only:
  - master
